### ISSUE TITLE
clé de journal pas trouvée

### ISSUE THREAD

**Issue by lofrez** [LeMoineau/milireader2pdf-Extension#1]
Bonjour,

J'ai chargé votre extension, mais lorsque j'essaye de générer un pdf depuis la page sur laquelle il y a mon journal au format "milibris", votre extension m'indique "clé de journal pas trouvée"...

Pouvez vous m'aider à faire fonctionner votre extension pour mon journal ;)

Merci d'avance

**Comment by LeMoineau** [comment]
Bonjour,

Merci de votre remarque, je m'étais en effet trompé sur une valeur. 
J'ai donc modifié pour corriger ce bug ! Plus qu'à installer la nouvelle version de l'extension et ça devrait refonctionner !

N'hésitez pas à revenir si ça ne fonctionne toujours pas.
Bonne soirée

(J'ai fait les tests de fonctionnement avec la nouvelle version de l'extension pour le journal suivant: https://kiosque.lindependant.fr/reader/preview/ba8ae7a0-64b0-4f3d-945f-46ac1e43d53c)

**Comment by lofrez** [comment]
Bonjour,

Merci pour votre retour et votre rapide réactivité.
En effet, votre extension fonctionne sur le journal de l'indépendant, mais pas sur celui que je consulte (Républicain Lorrain).
Je vous met ci-joint deux copies d'écran de la page de consultation du journal. Est ce que le problème ne viendrais pas du fait que le lecteur est embarqué dans une page web (ce qui semble ne pas etre le cas sur le site de l'indépendant) ?

Merci encore pour votre aide

![RL mili](https://user-images.githubusercontent.com/37960209/141424527-46b3d1c1-1d2a-410d-aa60-28ac86a007e0.jpg)
![RL2 mili](https://user-images.githubusercontent.com/37960209/141424532-ace36a6b-963e-4f5c-9fe5-8b1ec50af11e.jpg)
e
